package org.demo.jbpm.models;

import org.kie.api.remote.Remotable;

/**
 * This class was automatically generated by the data modeler tool.
 */

@Remotable
public class Application implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long id;

	private org.demo.jbpm.models.FinancialInformation financialInformation;
	private java.util.List<org.demo.jbpm.models.EmploymentDetails> employmentDetails;
	private org.demo.jbpm.models.PersonalDetails personalDetails;
	private org.demo.jbpm.models.CreditDetails creditDetails;
	private org.demo.jbpm.models.CompanyDetails companyDetails;

	public Application() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public org.demo.jbpm.models.FinancialInformation getFinancialInformation() {
		return this.financialInformation;
	}

	public void setFinancialInformation(org.demo.jbpm.models.FinancialInformation financialInformation) {
		this.financialInformation = financialInformation;
	}

	public java.util.List<org.demo.jbpm.models.EmploymentDetails> getEmploymentDetails() {
		return this.employmentDetails;
	}

	public void setEmploymentDetails(java.util.List<org.demo.jbpm.models.EmploymentDetails> employmentDetails) {
		this.employmentDetails = employmentDetails;
	}

	public org.demo.jbpm.models.PersonalDetails getPersonalDetails() {
		return this.personalDetails;
	}

	public void setPersonalDetails(org.demo.jbpm.models.PersonalDetails personalDetails) {
		this.personalDetails = personalDetails;
	}

	public org.demo.jbpm.models.CreditDetails getCreditDetails() {
		return this.creditDetails;
	}

	public void setCreditDetails(org.demo.jbpm.models.CreditDetails creditDetails) {
		this.creditDetails = creditDetails;
	}

	public org.demo.jbpm.models.CompanyDetails getCompanyDetails() {
		return this.companyDetails;
	}

	public void setCompanyDetails(org.demo.jbpm.models.CompanyDetails companyDetails) {
		this.companyDetails = companyDetails;
	}

	public Application(java.lang.Long id,
			org.demo.jbpm.models.FinancialInformation financialInformation,
			java.util.List<org.demo.jbpm.models.EmploymentDetails> employmentDetails,
			org.demo.jbpm.models.PersonalDetails personalDetails,
			org.demo.jbpm.models.CreditDetails creditDetails,
			org.demo.jbpm.models.CompanyDetails companyDetails) {
		this.id = id;
		this.financialInformation = financialInformation;
		this.employmentDetails = employmentDetails;
		this.personalDetails = personalDetails;
		this.creditDetails = creditDetails;
		this.companyDetails = companyDetails;
	}

}
