package org.demo.jbpm.models;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ExistingLoanDetails implements java.io.Serializable {

  static final long serialVersionUID = 1L;

  private java.lang.Long id;
  private java.lang.String loanType;
  private java.math.BigDecimal monthlyInstallmentAmount;
  private java.math.BigDecimal outstandingBalanceAmount;
  private java.lang.String debtOwnership;
  private java.lang.String lenderName;
  private java.math.BigDecimal loanAmount;
  public ExistingLoanDetails() {}

  public java.lang.Long getId() {
    return this.id;
  }

  public void setId(java.lang.Long id) {
    this.id = id;
  }

  public java.lang.String getLoanType() {
    return this.loanType;
  }

  public void setLoanType(java.lang.String loanType) {
    this.loanType = loanType;
  }

  public java.math.BigDecimal getMonthlyInstallmentAmount() {
    return this.monthlyInstallmentAmount;
  }

  public void setMonthlyInstallmentAmount(java.math.BigDecimal monthlyInstallmentAmount) {
    this.monthlyInstallmentAmount = monthlyInstallmentAmount;
  }

  public java.math.BigDecimal getOutstandingBalanceAmount() {
    return this.outstandingBalanceAmount;
  }

  public void setOutstandingBalanceAmount(java.math.BigDecimal outstandingBalanceAmount) {
    this.outstandingBalanceAmount = outstandingBalanceAmount;
  }

  public java.lang.String getDebtOwnership() {
    return this.debtOwnership;
  }

  public void setDebtOwnership(java.lang.String debtOwnership) {
    this.debtOwnership = debtOwnership;
  }

  public java.lang.String getLenderName() {
    return this.lenderName;
  }

  public void setLenderName(java.lang.String lenderName) {
    this.lenderName = lenderName;
  }

  public java.math.BigDecimal getLoanAmount() {
    return this.loanAmount;
  }

  public void setLoanAmount(java.math.BigDecimal loanAmount) {
    this.loanAmount = loanAmount;
  }

  public ExistingLoanDetails(java.lang.Long id, java.lang.String loanType, java.math.BigDecimal monthlyInstallmentAmount,
      java.math.BigDecimal outstandingBalanceAmount, java.lang.String debtOwnership, java.lang.String lenderName,
      java.math.BigDecimal loanAmount) {
    this.id = id;
    this.loanType = loanType;
    this.monthlyInstallmentAmount = monthlyInstallmentAmount;
    this.outstandingBalanceAmount = outstandingBalanceAmount;
    this.debtOwnership = debtOwnership;
    this.lenderName = lenderName;
    this.loanAmount = loanAmount;
  }

}
