package org.demo.jbpm.models;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StatusList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long id;

	private java.util.List<org.demo.jbpm.models.Status> status;

	public StatusList() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.util.List<org.demo.jbpm.models.Status> getStatus() {
		return this.status;
	}

	public void setStatus(java.util.List<org.demo.jbpm.models.Status> status) {
		this.status = status;
	}

	public StatusList(java.lang.Long id, java.util.List<org.demo.jbpm.models.Status> status) {
		this.id = id;
		this.status = status;
	}

}
