package org.demo.jbpm.models;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Status implements java.io.Serializable {
	
	static final long serialVersionUID = 1L;

	private String name;
	private String status;
	private Long dateStarted;
	private Long dateCompleted;

	public Status() {
	}

	public Status(String name, String status, Long dateStarted, Long dateCompleted) {
		super();
		this.name = name;
		this.status = status;
		this.dateStarted = dateStarted;
		this.dateCompleted = dateCompleted;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Long getDateStarted() {
		return dateStarted;
	}

	public void setDateStarted(Long dateStarted) {
		this.dateStarted = dateStarted;
	}

	public Long getDateCompleted() {
		return dateCompleted;
	}

	public void setDateCompleted(Long dateCompleted) {
		this.dateCompleted = dateCompleted;
	}

	@Override
	public String toString() {
		return "Status [name=" + name + ", status=" + status + ", dateStarted=" + dateStarted + ", dateCompleted="
				+ dateCompleted + "]";
	}

}
